### ISSUE TITLE
不换网卡用这个可行吗

### ISSUE THREAD

**Issue by Mirakelor** [Zrc00/Lenovo-Xiaoxin-15ARE-AMD-4800U-Hackintosh#10]
https://github.com/chris1111/Wireless-USB-OC-Big-Sur-Adapter
里面提到了Realtek 802.11ac的驱动，似乎可以直接试试

**Comment by Zrc00** [comment]
这似乎是一个Realtek USB WiFi适配器的驱动，我感觉这不一定在RTL8822CE上有效
其列举的支持设备也不包括这个
________________________________
发件人: Mirakelor ***@***.***>
发送时间: Sunday, July 21, 2024 9:34:29 PM
收件人: Zrc00/Lenovo-Xiaoxin-15ARE-AMD-4800U-Hackintosh ***@***.***>
抄送: Subscribed ***@***.***>
主题: [Zrc00/Lenovo-Xiaoxin-15ARE-AMD-4800U-Hackintosh] 不换网卡用这个可行吗 (Issue #10)


https://github.com/chris1111/Wireless-USB-OC-Big-Sur-Adapter
里面提到了Realtek 802.11ac的驱动，似乎可以直接试试

―

**Comment by Mirakelor** [comment]
远景论坛上好像有人说成功了。我去试试。

**Comment by Zrc00** [comment]
能否给个链接，想研究一下
________________________________
发件人: Mirakelor ***@***.***>
发送时间: Sunday, July 21, 2024 9:49:12 PM
收件人: Zrc00/Lenovo-Xiaoxin-15ARE-AMD-4800U-Hackintosh ***@***.***>
抄送: Zrc00 ***@***.***>; Comment ***@***.***>
主题: Re: [Zrc00/Lenovo-Xiaoxin-15ARE-AMD-4800U-Hackintosh] 不换网卡用这个可行吗 (Issue #10)


远景论坛上好像有人说成功了。我去试试。

―

**Comment by Mirakelor** [comment]
https://bbs.pcbeta.com/viewthread-1845893-1-1.html

**Comment by Mirakelor** [comment]
天哪他也是USB网卡

**Comment by Zrc00** [comment]
已经尝试，确认无效
________________________________
发件人: Mirakelor ***@***.***>
发送时间: Sunday, July 21, 2024 10:06:28 PM
收件人: Zrc00/Lenovo-Xiaoxin-15ARE-AMD-4800U-Hackintosh ***@***.***>
抄送: Zrc00 ***@***.***>; Comment ***@***.***>
主题: Re: [Zrc00/Lenovo-Xiaoxin-15ARE-AMD-4800U-Hackintosh] 不换网卡用这个可行吗 (Issue #10)


天哪他也是USB网卡

―

**Comment by Mirakelor** [comment]
OK.Thank You😊
