### ISSUE TITLE
联想小新pro13测试成功

### ISSUE THREAD

**Issue by zhjcreator** [Zrc00/Lenovo-Xiaoxin-15ARE-AMD-4800U-Hackintosh#4]
感谢分享！
目前异常功能：睡眠，麦克风，核显驱动已知bug。
还有4800u额外再带4k屏的话稍微勉强了点，单屏明显流畅太多。

作者可不可以测试下https://github.com/zhen-zen/YogaSMC/
可以增加风扇控制，充电控制，键盘背光控制。
它的说明我有点看不懂。

**Comment by Zrc00** [comment]
感谢使用本仓库的EFI🎉
他好像说只支持这些机型，我也不确定小新机型是否支持。
![image](https://github.com/Zrc00/Lenovo-Xiaoxin-15ARE-AMD-4800U-Hackintosh/assets/133766567/c8874c7b-14ed-4f79-aa68-f6fcaa0a725e)
你可以搭配翻译进行查看
祝生活愉快ヾ(•ω•`)o

**Comment by zhjcreator** [comment]
补充说明下，使用yogasmc的acpi后，可以调充电是电池保护模式或者充满了。不过风扇和键盘背光还是调不了，可能和我SSDT-WMIS编译失败相关。
