### ISSUE TITLE
我小新pro13 原装的pm981a是不是也得换

### ISSUE THREAD

**Issue by GreenGh0st** [Zrc00/Lenovo-Xiaoxin-15ARE-AMD-4800U-Hackintosh#5]
大佬你这个可以睡眠唤醒吗，所有usb口都能用吗，麦克风能用吗

**Comment by Zrc00** [comment]
不可以哦，睡眠还是唤醒不了
USB口都能用，无需禁用XHCI0或XHCI1
麦克风无效，但可以试试这个新的开源kext，叫AMDMicrophone.kext，Github能搜到，适用范围比较小，我就不支持，你试试你的
期待你的答复
